name: Build and publish docker image

on:
  push:
    branches:
      - master
  schedule:
    # Every 14th day of the month at 6:30 AM
    - cron: '30 6 14 * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build and copy module
        run: |
          make
          cp -f ratelimit.so docker/
      - name: Publish redis image
        uses: elgohr/Publish-Docker-Github-Action@eb53b3ec07136a6ebaed78d8135806da64f7c7e2 # v5
        with:
          name: maxr1998/redis-custom
          workdir: docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 6-alpine